// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fullClean.Infractucture;

namespace fullClean.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fullClean.Dominio.Models.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("codproduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detailproduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameproduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("stockstore")
                        .HasColumnType("int");

                    b.Property<int>("stockwarehouse")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("fullClean.Dominio.Models.Sales", b =>
                {
                    b.Property<int>("salesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("codproduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detailproduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameproduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("salesId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("fullClean.Dominio.Models.SalesAndProducts", b =>
                {
                    b.Property<int>("Idproducts")
                        .HasColumnType("int");

                    b.Property<int>("Idsales")
                        .HasColumnType("int");

                    b.HasKey("Idproducts", "Idsales");

                    b.HasIndex("Idsales");

                    b.ToTable("SalesAndProducts");
                });

            modelBuilder.Entity("fullClean.Dominio.Models.SalesAndProducts", b =>
                {
                    b.HasOne("fullClean.Dominio.Models.Products", "products")
                        .WithMany("salesAndProducts")
                        .HasForeignKey("Idproducts")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fullClean.Dominio.Models.Sales", "sales")
                        .WithMany("SalesAndProductslist")
                        .HasForeignKey("Idsales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("products");

                    b.Navigation("sales");
                });

            modelBuilder.Entity("fullClean.Dominio.Models.Products", b =>
                {
                    b.Navigation("salesAndProducts");
                });

            modelBuilder.Entity("fullClean.Dominio.Models.Sales", b =>
                {
                    b.Navigation("SalesAndProductslist");
                });
#pragma warning restore 612, 618
        }
    }
}
